/**
 * Minimal confusables map: non-Latin code points that render like Latin
 * letters and are used to slip phrases past literal matching. NFKC already
 * folds fullwidth/compatibility forms; this covers the Cyrillic and Greek
 * lookalikes NFKC leaves alone. Data-driven so a content feed can extend it.
 */
export const CONFUSABLE_TO_LATIN: Readonly<Record<string, string>> = {
  // Cyrillic lowercase
  а: "a",
  в: "b",
  е: "e",
  ё: "e",
  к: "k",
  м: "m",
  н: "h",
  о: "o",
  р: "p",
  с: "c",
  т: "t",
  у: "y",
  х: "x",
  і: "i",
  ѕ: "s",
  ј: "j",
  ԁ: "d",
  ԛ: "q",
  ѡ: "w",
  // Cyrillic uppercase
  А: "A",
  В: "B",
  Е: "E",
  К: "K",
  М: "M",
  Н: "H",
  О: "O",
  Р: "P",
  С: "C",
  Т: "T",
  У: "Y",
  Х: "X",
  І: "I",
  Ѕ: "S",
  Ј: "J",
  // Greek lowercase
  α: "a",
  ε: "e",
  η: "n",
  ι: "i",
  κ: "k",
  ν: "v",
  ο: "o",
  ρ: "p",
  τ: "t",
  υ: "u",
  // Greek uppercase
  Α: "A",
  Β: "B",
  Ε: "E",
  Ζ: "Z",
  Η: "H",
  Ι: "I",
  Κ: "K",
  Μ: "M",
  Ν: "N",
  Ο: "O",
  Ρ: "P",
  Τ: "T",
  Υ: "Y",
  Χ: "X",
};
